version: '3'
services:
    mongo:
        image: "mongo:4.0.2"
        network_mode: host
    {{prj_name}}:
      volumes:
        - .envs/local.env:/app/deployments/.envs/local.env
      build:
        context: ..
        dockerfile: deployments/Dockerfile
      depends_on:
        - mongo
      network_mode: host
