version: '3'
services:
    {{ cookiecutter.service }}:
      volumes:
        - .envs/local.env:/app/deployments/.envs/local.env
      build:
        context: ..
        dockerfile: deployments/Dockerfile
      depends_on: []
      network_mode: host
